export const adminAppStylesCalendar = {
  scheduleTimes: {
    gap: 8,
    flex: 1,
  },
  scheduleTimeCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.22)",
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    padding: 8,
    gap: 6,
  },
  scheduleTimeCardLight: {
    borderColor: "rgba(15, 23, 42, 0.14)",
    backgroundColor: "#f8fafc",
  },
  scheduleTimeLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: "#94a3b8",
  },
  scheduleTimeValue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#e2e8f0",
  },
  scheduleControlRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  scheduleStepButton: {
    minWidth: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
    backgroundColor: "rgba(148, 163, 184, 0.18)",
    paddingVertical: 5,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  scheduleStepButtonLight: {
    borderColor: "rgba(15, 23, 42, 0.18)",
    backgroundColor: "#e2e8f0",
  },
  scheduleStepButtonText: {
    color: "#e2e8f0",
    fontWeight: "700",
    fontSize: 11,
  },
  scheduleStepButtonTextLight: {
    color: "#0f172a",
  },
  scheduleMeridiemButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(99, 102, 241, 0.45)",
    backgroundColor: "rgba(99, 102, 241, 0.22)",
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  scheduleMeridiemGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  scheduleMeridiemButtonActive: {
    borderColor: "rgba(59, 130, 246, 0.65)",
    backgroundColor: "rgba(59, 130, 246, 0.35)",
  },
  scheduleMeridiemButtonLight: {
    borderColor: "rgba(37, 99, 235, 0.34)",
    backgroundColor: "#dbeafe",
  },
  scheduleMeridiemButtonActiveLight: {
    borderColor: "rgba(30, 64, 175, 0.6)",
    backgroundColor: "#2563eb",
  },
  scheduleMeridiemText: {
    color: "#e2e8f0",
    fontWeight: "700",
    fontSize: 11,
  },
  scheduleMeridiemTextLight: {
    color: "#1e3a8a",
  },
  scheduleMeridiemTextActive: {
    color: "#f8fafc",
  },
  scheduleInput: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 10,
    paddingHorizontal: 10,
    height: 38,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    color: "#e2e8f0",
    flex: 1,
    textAlign: "center",
  },
  scheduleInputDisabled: { opacity: 0.6 },
  scheduleDash: { color: "#94a3b8", fontSize: 14 },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  calendarControls: { flexDirection: "row", alignItems: "center", gap: 8 },
  calendarButton: {
    backgroundColor: "rgba(148, 163, 184, 0.2)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  calendarButtonLight: { backgroundColor: "#e2e8f0" },
  calendarButtonText: { color: "#e2e8f0", fontWeight: "700" },
  calendarButtonTextLight: { color: "#0f172a" },
  calendarLabel: { color: "#e2e8f0", fontWeight: "700" },
  calendarLabelLight: { color: "#0f172a" },
  calendarGrid: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 8,
  },
  calendarDayHead: {
    width: "13.5%",
    textAlign: "center",
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
  },
  calendarCell: {
    width: "13.5%",
    aspectRatio: 1,
    borderRadius: 10,
    backgroundColor: "rgba(148, 163, 184, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  calendarCellLight: {
    backgroundColor: "#f1f5f9",
    borderColor: "rgba(15, 23, 42, 0.12)",
  },
  calendarCellEmpty: {
    backgroundColor: "transparent",
    borderColor: "transparent",
  },
  calendarCellToday: {
    backgroundColor: "#2f5bff",
    borderColor: "transparent",
    shadowColor: "#2f5bff",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  calendarCellTodayLight: {
    backgroundColor: "#2563eb",
    borderColor: "transparent",
  },
  calendarCellText: { color: "#e2e8f0", fontWeight: "600" },
  calendarCellTextLight: { color: "#0f172a" },
  calendarCellTextEmpty: { color: "transparent" },
  calendarCellTextToday: { color: "#f8fafc" },
  calendarCellTextTodayLight: { color: "#f8fafc" },
} as const;
