export const adminAppStylesFooter = {
  inlineButton: {
    backgroundColor: "#ef4444",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inlineButtonText: { color: "#fff7ed", fontSize: 11, fontWeight: "700" },
  inlineButtonLight: { backgroundColor: "#dc2626" },
  inlineButtonTextLight: { color: "#ffffff" },
  inlineButtonDisabled: { opacity: 0.6 },
  divider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.08)",
    marginVertical: 12,
  },
  dividerLight: { backgroundColor: "rgba(15, 23, 42, 0.12)" },
  workingCard: {
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    borderRadius: 18,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
  },
  workingCardLight: { backgroundColor: "#f8fafc" },
  workingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  workingLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(59, 130, 246, 0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#e2e8f0", fontWeight: "700", fontSize: 12 },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(34, 197, 94, 0.18)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#34d399",
  },
  statusPillText: { color: "#d1fae5", fontSize: 11, fontWeight: "700" },
  statusPillOut: { backgroundColor: "rgba(148, 163, 184, 0.18)" },
  statusDotOut: { backgroundColor: "#94a3b8" },
  statusPillTextOut: { color: "#e2e8f0" },
  footerNote: {
    textAlign: "center",
    color: "rgba(226, 232, 240, 0.6)",
    marginTop: 14,
    fontSize: 12,
  },
  footerNoteLight: { color: "#64748b" },
  inlineButtonIn: {
    backgroundColor: "#22c55e",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inlineButtonTextIn: { color: "#0f172a", fontSize: 11, fontWeight: "700" },
  inlineButtonInLight: { backgroundColor: "#16a34a" },
  inlineButtonTextInLight: { color: "#ffffff" },
} as const;
