export const adminAppStylesBase = {
  gradient: { flex: 1 },
  safe: { flex: 1 },
  keyboardWrap: { flex: 1 },
  container: { padding: 20, paddingBottom: 40, gap: 16 },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  brandLogo: { width: 118, height: 44 },
  brandTextBlock: {
    flex: 1,
    minWidth: 160,
  },
  title: { fontSize: 24, fontWeight: "700", color: "#eef2ff" },
  subtitle: { color: "rgba(226, 232, 240, 0.7)", marginTop: 4, fontSize: 13 },
  headerActions: {
    marginLeft: "auto",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    flexShrink: 1,
    justifyContent: "flex-end",
  },
  languageSelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  languageSelectorLight: { backgroundColor: "#e2e8f0" },
  languageLabel: {
    color: "#f9f4ea",
    fontWeight: "600",
    fontSize: 11,
  },
  languageLabelLight: { color: "#0f172a" },
  languageOption: {
    borderRadius: 999,
    backgroundColor: "rgba(148, 163, 184, 0.35)",
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  languageOptionLight: { backgroundColor: "#cbd5e1" },
  languageOptionActive: { backgroundColor: "#2f5bff" },
  languageOptionActiveLight: { backgroundColor: "#2563eb" },
  languageOptionText: {
    color: "#f8fafc",
    fontWeight: "700",
    fontSize: 11,
    letterSpacing: 0.4,
  },
  languageOptionTextLight: { color: "#0f172a" },
  languageOptionTextActive: { color: "#f8fafc" },
  themeToggle: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  headerLogoutButton: { backgroundColor: "rgba(239, 68, 68, 0.7)" },
  headerLogoutButtonLight: { backgroundColor: "#ef4444" },
  themeToggleText: {
    color: "#f9f4ea",
    fontWeight: "600",
    fontSize: 12,
  },
  headerLogoutText: { color: "#ffffff" },
  headerLogoutTextLight: { color: "#ffffff" },
  tabRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  tabShell: {
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    borderRadius: 999,
    padding: 6,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  tabShellLight: { backgroundColor: "#e2e8f0" },
  tenantPill: {
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 6,
  },
  tenantPillText: {
    color: "#dbeafe",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  tenantPillTextLight: { color: "#1e3a8a" },
  tab: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  tabActive: { backgroundColor: "#2f5bff" },
  tabLocationSwitch: { backgroundColor: "#2563eb" },
  tabLocationSwitchLight: { backgroundColor: "#2563eb" },
  tabDanger: { backgroundColor: "rgba(239, 68, 68, 0.7)" },
  tabText: { color: "#f9f4ea", fontWeight: "600", fontSize: 12 },
  titleLight: { color: "#0f172a" },
  subtitleLight: { color: "#475569" },
  themeToggleLight: { backgroundColor: "#e2e8f0" },
  themeToggleTextLight: { color: "#0f172a" },
  tabLight: { backgroundColor: "#e2e8f0" },
  tabActiveLight: { backgroundColor: "#2563eb" },
  tabDangerLight: { backgroundColor: "#ef4444" },
  tabTextLight: { color: "#0f172a" },
  tabTextLightActive: { color: "#f8fafc" },
  tabTextLightDanger: { color: "#f8fafc" },
  card: {
    backgroundColor: "rgba(16, 23, 35, 0.65)",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    shadowColor: "#0f172a",
    shadowOpacity: 0.4,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#e2e8f0",
    marginBottom: 12,
  },
  cardLight: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(15, 23, 42, 0.08)",
  },
  cardTitleLight: { color: "#0f172a" },
  label: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    color: "#94a3b8",
    marginTop: 10,
    marginBottom: 6,
  },
  labelLight: { color: "#475569" },
  input: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 14,
    paddingHorizontal: 14,
    height: 44,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    marginBottom: 8,
    color: "#e2e8f0",
  },
  inputCompact: {
    marginTop: 8,
    marginBottom: 0,
  },
  tipCard: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    backgroundColor: "rgba(15, 23, 42, 0.35)",
    padding: 10,
    gap: 8,
  },
  employeeMessageTabs: {
    paddingRight: 8,
  },
  employeeMessageInput: {
    minHeight: 96,
    textAlignVertical: "top",
    paddingTop: 10,
  },
  statusText: { marginTop: 8, color: "#cbd5f5" },
  helperText: { color: "#94a3b8", marginTop: 8, fontSize: 12 },
  inputLight: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(15, 23, 42, 0.12)",
    color: "#0f172a",
  },
  statusTextLight: { color: "#334155" },
  helperTextLight: { color: "#64748b" },
  button: {
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
  },
  primary: { backgroundColor: "#2f5bff" },
  primaryText: { fontWeight: "700", color: "#eef2ff" },
  primaryTextLight: { color: "#f8fafc" },
  secondaryButton: {
    marginTop: 8,
    backgroundColor: "rgba(148, 163, 184, 0.16)",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignSelf: "flex-start",
  },
  secondaryButtonText: { fontSize: 12, fontWeight: "600", color: "#e2e8f0" },
  secondaryButtonLight: { backgroundColor: "#e2e8f0" },
  secondaryButtonTextLight: { color: "#0f172a" },
} as const;
