export const adminAppStylesSchedule = {
  userQuickList: {
    gap: 4,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    backgroundColor: "rgba(15, 23, 42, 0.25)",
    marginBottom: 8,
  },
  userQuickListLight: {
    borderColor: "rgba(15, 23, 42, 0.12)",
    backgroundColor: "#f8fafc",
  },
  userList: { maxHeight: 260, marginTop: 8 },
  userListContent: { paddingBottom: 8 },
  reportSectionTitle: { marginTop: 14, fontSize: 16, marginBottom: 8 },
  reportTotalsGrid: {
    marginTop: 8,
    marginBottom: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    backgroundColor: "rgba(15, 23, 42, 0.38)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    padding: 10,
  },
  reportTotalsGridLight: {
    backgroundColor: "#f8fafc",
    borderColor: "rgba(15, 23, 42, 0.12)",
  },
  reportTotalsTile: {
    minWidth: 120,
    flexGrow: 1,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  reportTotalsLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: "#94a3b8",
  },
  reportTotalsValue: {
    marginTop: 4,
    fontSize: 16,
    fontWeight: "700",
    color: "#e2e8f0",
  },
  reportRowMain: {
    flex: 1,
    paddingRight: 8,
    gap: 2,
  },
  scheduleTodayCard: {
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.22)",
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    padding: 10,
    gap: 8,
  },
  scheduleTodayCardLight: {
    borderColor: "rgba(15, 23, 42, 0.14)",
    backgroundColor: "#f8fafc",
  },
  scheduleTodayHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  scheduleTodayTitleWrap: {
    flex: 1,
    gap: 2,
  },
  scheduleTodayTitle: {
    color: "#e2e8f0",
    fontSize: 15,
    fontWeight: "700",
  },
  scheduleTodayTitleLight: {
    color: "#0f172a",
  },
  scheduleRoleTabs: {
    marginBottom: 0,
  },
  scheduleTodayRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    backgroundColor: "rgba(148, 163, 184, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  scheduleTodayRowLight: {
    borderColor: "rgba(15, 23, 42, 0.12)",
    backgroundColor: "#ffffff",
  },
  scheduleTodayRowMain: {
    flex: 1,
    gap: 2,
    paddingRight: 8,
  },
  scheduleTodayShift: {
    color: "#dbeafe",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
  },
  scheduleTodayShiftLight: {
    color: "#1e40af",
  },
  scheduleEmployeePicker: {
    marginTop: 2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    backgroundColor: "rgba(15, 23, 42, 0.38)",
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  scheduleEmployeePickerLight: {
    borderColor: "rgba(15, 23, 42, 0.14)",
    backgroundColor: "#f8fafc",
  },
  scheduleEmployeePickerText: {
    color: "#e2e8f0",
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
  },
  scheduleEmployeePickerTextLight: {
    color: "#0f172a",
  },
  scheduleEmployeePickerArrow: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "700",
    marginLeft: 10,
  },
  scheduleEmployeeMenu: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.22)",
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    padding: 10,
    gap: 8,
  },
  scheduleEmployeeMenuLight: {
    borderColor: "rgba(15, 23, 42, 0.14)",
    backgroundColor: "#ffffff",
  },
  scheduleEmployeeSearchInput: {
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    backgroundColor: "rgba(148, 163, 184, 0.12)",
    color: "#e2e8f0",
    paddingHorizontal: 10,
  },
  scheduleEmployeeSearchInputLight: {
    borderColor: "rgba(15, 23, 42, 0.14)",
    backgroundColor: "#f8fafc",
    color: "#0f172a",
  },
  scheduleEmployeeList: {
    maxHeight: 190,
  },
  scheduleEmployeeItem: {
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    backgroundColor: "rgba(148, 163, 184, 0.1)",
    paddingHorizontal: 10,
    justifyContent: "center",
    marginBottom: 6,
  },
  scheduleEmployeeItemLight: {
    borderColor: "rgba(15, 23, 42, 0.12)",
    backgroundColor: "#f8fafc",
  },
  scheduleEmployeeItemActive: {
    borderColor: "rgba(59, 130, 246, 0.45)",
    backgroundColor: "rgba(47, 91, 255, 0.3)",
  },
  scheduleEmployeeItemActiveLight: {
    borderColor: "rgba(37, 99, 235, 0.35)",
    backgroundColor: "#dbeafe",
  },
  scheduleEmployeeItemText: {
    color: "#e2e8f0",
    fontSize: 13,
    fontWeight: "600",
  },
  scheduleEmployeeItemTextLight: {
    color: "#0f172a",
  },
  scheduleEmployeeItemTextActive: {
    color: "#f8fafc",
  },
  scheduleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 10,
  },
  scheduleToggle: {
    backgroundColor: "rgba(148, 163, 184, 0.2)",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    minWidth: 110,
  },
  scheduleToggleActive: { backgroundColor: "#2f5bff" },
  scheduleToggleLight: { backgroundColor: "#e2e8f0" },
  scheduleToggleText: { color: "#e2e8f0", fontWeight: "600", fontSize: 12 },
  scheduleToggleTextLight: { color: "#0f172a" },
  scheduleToggleTextActive: { color: "#f8fafc" },
} as const;
