export const adminAppStylesListing = {
  secondaryButtonDanger: { backgroundColor: "#dc2626" },
  secondaryButtonDangerText: { color: "#ffffff" },
  rowActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  userRowActions: {
    width: "100%",
    justifyContent: "flex-start",
  },
  actionButtonCompact: {
    marginTop: 0,
    alignSelf: "auto",
  },
  actionButtonPrimary: {
    minWidth: 140,
    marginTop: 0,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  summaryTile: {
    backgroundColor: "rgba(148, 163, 184, 0.1)",
    borderRadius: 14,
    padding: 12,
    minWidth: 120,
    flexGrow: 1,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  summaryHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  summaryIcon: {
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: "rgba(15, 23, 42, 0.35)",
  },
  summaryIconUsers: { backgroundColor: "rgba(59, 130, 246, 0.35)" },
  summaryIconShield: { backgroundColor: "rgba(244, 114, 182, 0.35)" },
  summaryIconTime: { backgroundColor: "rgba(34, 197, 94, 0.35)" },
  summaryIconReports: { backgroundColor: "rgba(148, 163, 184, 0.35)" },
  summaryLabel: {
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#cbd5f5",
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#e2e8f0",
    marginTop: 6,
  },
  summaryTileLight: { backgroundColor: "#f8fafc" },
  summaryLabelLight: { color: "#64748b" },
  summaryValueLight: { color: "#0f172a" },
  toggleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
  },
  togglePill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "rgba(148, 163, 184, 0.2)",
  },
  toggleActive: { backgroundColor: "#2f5bff" },
  toggleDanger: { backgroundColor: "#dc2626" },
  toggleText: { fontSize: 11, fontWeight: "600", color: "#e2e8f0" },
  togglePillLight: { backgroundColor: "#e2e8f0" },
  toggleActiveLight: { backgroundColor: "#2563eb" },
  toggleTextLight: { color: "#0f172a" },
  toggleTextLightActive: { color: "#f8fafc" },
  listRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148, 163, 184, 0.14)",
  },
  liquorRowCard: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(148, 163, 184, 0.14)",
    gap: 8,
  },
  liquorRowHeader: {
    width: "100%",
    gap: 2,
  },
  liquorFormGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  liquorFieldHalf: {
    flexGrow: 1,
    flexBasis: 150,
    minWidth: 130,
  },
  liquorFieldThird: {
    flexGrow: 1,
    flexBasis: 96,
    minWidth: 88,
  },
  liquorFieldStat: {
    flexGrow: 1,
    flexBasis: 130,
    minWidth: 110,
  },
  liquorActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  liquorFilterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  liquorSectionCard: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    backgroundColor: "rgba(15, 23, 42, 0.28)",
    padding: 10,
    gap: 8,
  },
  liquorSectionCardLight: {
    borderColor: "rgba(15, 23, 42, 0.12)",
    backgroundColor: "#f8fafc",
  },
  liquorShockText: {
    color: "#fca5a5",
    fontWeight: "700",
  },
  liquorDeltaPositive: {
    color: "#22c55e",
    fontWeight: "700",
  },
  liquorDeltaNegative: {
    color: "#f87171",
    fontWeight: "700",
  },
  userListRow: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
  },
  userListMain: {
    width: "100%",
  },
  listActions: { flexDirection: "row", alignItems: "center", gap: 10 },
  listName: { fontSize: 14, fontWeight: "600", color: "#e2e8f0" },
  listMeta: { fontSize: 12, color: "#94a3b8" },
  listNameLight: { color: "#0f172a" },
  listMetaLight: { color: "#64748b" },
  companyOrderItemsWrap: {
    gap: 4,
    marginTop: 8,
  },
  companyOrderCartSection: {
    marginTop: 10,
    gap: 8,
  },
  companyOrderCartRow: {
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "rgba(15, 23, 42, 0.25)",
    gap: 8,
  },
  companyOrderCartActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  companyOrderStepButton: {
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.3)",
    borderRadius: 8,
    minWidth: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    backgroundColor: "rgba(59, 130, 246, 0.18)",
  },
  companyOrderStepButtonLight: {
    borderColor: "rgba(37, 99, 235, 0.35)",
    backgroundColor: "#eff6ff",
  },
  companyOrderStepButtonText: {
    color: "#dbeafe",
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 18,
  },
  companyOrderStepButtonTextLight: {
    color: "#1d4ed8",
  },
  companyOrderQtyBadge: {
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.3)",
    borderRadius: 8,
    minWidth: 56,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "rgba(15, 23, 42, 0.2)",
  },
  companyOrderQtyBadgeLight: {
    borderColor: "rgba(15, 23, 42, 0.18)",
    backgroundColor: "#f8fafc",
  },
  companyOrderQtyBadgeText: {
    color: "#e2e8f0",
    fontSize: 13,
    fontWeight: "700",
  },
  companyOrderQtyBadgeTextLight: {
    color: "#0f172a",
  },
  companyOrderRemoveButton: {
    marginLeft: "auto",
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.4)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(248, 113, 113, 0.12)",
  },
  companyOrderRemoveButtonLight: {
    borderColor: "rgba(220, 38, 38, 0.3)",
    backgroundColor: "#fef2f2",
  },
  companyOrderRemoveButtonText: {
    color: "#fecaca",
    fontSize: 12,
    fontWeight: "700",
  },
  companyOrderRemoveButtonTextLight: {
    color: "#b91c1c",
  },
  companyOrderExportRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  companyOrderQtyInput: {
    width: 82,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
    backgroundColor: "rgba(15, 23, 42, 0.2)",
    color: "#e2e8f0",
    paddingHorizontal: 10,
    textAlign: "center",
    fontWeight: "700",
  },
  companyOrderAddButton: {
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.3)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "rgba(59, 130, 246, 0.18)",
  },
  companyOrderAddButtonLight: {
    borderColor: "rgba(37, 99, 235, 0.35)",
    backgroundColor: "#eff6ff",
  },
  companyOrderAddButtonText: {
    color: "#dbeafe",
    fontSize: 12,
    fontWeight: "700",
  },
  companyOrderAddButtonTextLight: {
    color: "#1d4ed8",
  },
} as const;
