import type { UiLang } from "../../../lib/ui-language";

export const auditCopy: Record<UiLang, Record<string, string>> = {
  en: {
    title: "Audit Log",
    period: "Period",
    weekly: "Weekly",
    biweekly: "Bi-Weekly",
    monthly: "Monthly",
    custom: "Custom",
    from: "From",
    to: "To",
    employee: "Employee",
    allEmployees: "All Employees",
    type: "Type",
    allTypes: "All Types",
    limit: "Limit",
    running: "Running...",
    runReport: "Run Report",
    exportExcel: "Export Excel",
    noRecords: "No audit records found.",
    results: "Audit Log Results",
    records: "Records",
    dateTime: "Date & Time",
    office: "Office",
    group: "Group",
    notes: "Notes",
    photos: "Punch Photos",
    empty: "—",
  },
  es: {
    title: "Bitácora de Auditoría",
    period: "Periodo",
    weekly: "Semanal",
    biweekly: "Quincenal",
    monthly: "Mensual",
    custom: "Personalizado",
    from: "Desde",
    to: "Hasta",
    employee: "Empleado",
    allEmployees: "Todos los empleados",
    type: "Tipo",
    allTypes: "Todos los tipos",
    limit: "Límite",
    running: "Ejecutando...",
    runReport: "Generar reporte",
    exportExcel: "Exportar Excel",
    noRecords: "No se encontraron registros de auditoría.",
    results: "Resultados de auditoría",
    records: "Registros",
    dateTime: "Fecha y hora",
    office: "Ubicación",
    group: "Grupo",
    notes: "Notas",
    photos: "Fotos de marcación",
    empty: "—",
  },
};
