export type TipsLang = "en" | "es";

export const tipsCopy: Record<TipsLang, Record<string, string>> = {
  en: {
    title: "Tips Report",
    period: "Period",
    weekly: "Weekly",
    biweekly: "Bi-Weekly",
    monthly: "Monthly",
    custom: "Custom",
    from: "From",
    to: "To",
    employee: "Employee",
    allServers: "All Servers",
    runReport: "Run Report",
    running: "Running...",
    downloadPdf: "Download PDF",
    noData: "No tip records found for this date range.",
    totalTips: "Total Tips",
    cash: "Cash",
    creditCard: "Credit Card",
    date: "Date",
    allGood: "Unable to load tips report",
  },
  es: {
    title: "Reporte de Propinas",
    period: "Período",
    weekly: "Semanal",
    biweekly: "Quincenal",
    monthly: "Mensual",
    custom: "Personalizado",
    from: "Desde",
    to: "Hasta",
    employee: "Empleado",
    allServers: "Todos los Meseros",
    runReport: "Ejecutar Reporte",
    running: "Procesando...",
    downloadPdf: "Descargar PDF",
    noData: "No se encontraron propinas para este rango.",
    totalTips: "Total de Propinas",
    cash: "Efectivo",
    creditCard: "Tarjeta",
    date: "Fecha",
    allGood: "No se pudo cargar el reporte de propinas",
  },
};
